-- auto Generated on 2024-02-01
-- DROP TABLE IF EXISTS quality;
CREATE TABLE quality(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	app_user_id INT (11) NOT NULL DEFAULT -1 COMMENT '发布用户ID',
	app_user_type INT (11) NOT NULL DEFAULT -1 COMMENT '发布用户类型',
	`type` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '类别：0 夏装 1 冬装',
	demand DECIMAL (13,4) NOT NULL DEFAULT -1 COMMENT '需求量 单位（吨）',
	quality_per VARCHAR (50) NOT NULL DEFAULT '' COMMENT '质量百分比  A:30,B:60,C:10',
	address VARCHAR (50) NOT NULL DEFAULT '' COMMENT '地址',
	quality_type TINYINT (3) NOT NULL DEFAULT 0 COMMENT '供需关系 0 供货 1需求',
	`status` TINYINT (3) NOT NULL DEFAULT 0 COMMENT '-1 删除 0 创建 1上架',
	page_view BIGINT (15) NOT NULL DEFAULT -1 COMMENT '浏览量',
	create_time DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'createTime',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'quality';
